In [3]:
import numpy as np

In [1]:
lst_nums = [2,5,7,11,13,17,23,31,37,41,43,47]

In [4]:
np.mean(lst_nums)

23.083333333333332

In [5]:
ary_nums = np.array(lst_nums)
ary_nums.mean()

23.083333333333332

In [6]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
np.arange(-7.1,7,.5)

array([-7.1, -6.6, -6.1, -5.6, -5.1, -4.6, -4.1, -3.6, -3.1, -2.6, -2.1,
       -1.6, -1.1, -0.6, -0.1,  0.4,  0.9,  1.4,  1.9,  2.4,  2.9,  3.4,
        3.9,  4.4,  4.9,  5.4,  5.9,  6.4,  6.9])

In [11]:
np.zeros([4])

array([0., 0., 0., 0.])

In [15]:
np.ones([3,3])[0]

array([1., 1., 1.])

In [26]:
Names = ["Jevon", "Dawn","Kayleigh","Jadene","Kennedy", "Kaydee","Ansh","Flynn","Kier","Clarence"]
math_grades = [80,50,60,70,60,100,70,70,70,60]
science_grades = [90,80,50,50,60,50,90,70,80,90]
history_grades = [60,90,50,90,100,100,100,100,90,70]

In [33]:
average_grade = np.zeros(10)
print(average_grade)

for idx,name in enumerate(Names):
  average_grade[idx] = np.mean([math_grades[idx], science_grades[idx], history_grades[idx]])
  
for idx, name in enumerate(Names):
  print(f"Average for {name}: {average_grade[idx]} ")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Average for Jevon: 76.66666666666667 
Average for Dawn: 73.33333333333333 
Average for Kayleigh: 53.333333333333336 
Average for Jadene: 70.0 
Average for Kennedy: 73.33333333333333 
Average for Kaydee: 83.33333333333333 
Average for Ansh: 86.66666666666667 
Average for Flynn: 80.0 
Average for Kier: 80.0 
Average for Clarence: 73.33333333333333 


In [35]:
np.linspace(0,1,21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [36]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [37]:
np.linspace(10,1000,100)

array([  10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,   90.,
        100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,  180.,
        190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,  270.,
        280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,  360.,
        370.,  380.,  390.,  400.,  410.,  420.,  430.,  440.,  450.,
        460.,  470.,  480.,  490.,  500.,  510.,  520.,  530.,  540.,
        550.,  560.,  570.,  580.,  590.,  600.,  610.,  620.,  630.,
        640.,  650.,  660.,  670.,  680.,  690.,  700.,  710.,  720.,
        730.,  740.,  750.,  760.,  770.,  780.,  790.,  800.,  810.,
        820.,  830.,  840.,  850.,  860.,  870.,  880.,  890.,  900.,
        910.,  920.,  930.,  940.,  950.,  960.,  970.,  980.,  990.,
       1000.])

In [39]:
Candidates = np.linspace(-1000,1000,2001)
print(Candidates)

for candidate in Candidates:
  if(candidate**2 - 5*candidate + 6 == 0):
    print(f"Just found a possible answer {candidate}")

[-1000.  -999.  -998. ...   998.   999.  1000.]
Just found a possible answer 2.0
Just found a possible answer 3.0
